### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by godmar** [bztsrc/qemu-raspi3#5]
Naive question - how do I build this on Ubuntu 16.04-2 LTS?

```
$ git clone git@github.com:bztsrc/qemu-raspi3.git
$ cd qemu-raspi3/
~/qemu-raspi3$ mkdir build
~/qemu-raspi3$ cd build
~/qemu-raspi3/build$ ../configure --target-list=aarch64-softmmu,aarch64-linux-user --enable-modules --enable-tcg-interpreter --enable-debug-tcg --prefix=/opt/scratch/rpi3

ERROR: DTC (libfdt) version >= 1.4.2 not present. Your options:
         (1) Preferred: Install the DTC (libfdt) devel package
         (2) Fetch the DTC submodule, using:
             git submodule update --init dtc
```
I install libfdt-dev via the package manager, but it's 1.4.0:

```
$ sudo apt-cache show libfdt-dev
Package: libfdt-dev
Priority: extra
Section: libdevel
Installed-Size: 115
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Hector Oron <zumbi@debian.org>
Architecture: amd64
Source: device-tree-compiler
Version: 1.4.0+dfsg-2
Depends: libfdt1 (= 1.4.0+dfsg-2)
Filename: pool/main/d/device-tree-compiler/libfdt-dev_1.4.0+dfsg-2_amd64.deb
Size: 20474
MD5sum: 6c1441305cd548d4692bf791544824e4
SHA1: 6d5deea3f16f37268c44b2ea6d5895a0cdc75aa1
SHA256: 1d35778c2db1b5b47123c2ea82ae55f1ae7de1039b1a7e750f98d5484d28599f
Description-en: Flat Device Trees manipulation library - development files
 This is a library containing functions for manipulating Flat Device Trees.
 .
 This package contains the files needed for development against libfdt.
Description-md5: ad28e5f86214823e1f8f3d325c48bfcf
Homepage: https://git.kernel.org/cgit/utils/dtc/dtc.git
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
```

so I tried option B:
```
~/qemu-raspi3/build$ cd ..
~/qemu-raspi3$ git submodule update --init dtc
error: pathspec 'dtc' did not match any file(s) known to git.
```

I updated git:
```
~/qemu-raspi3$ git --version
git version 2.15.1
```

The default instructions for qemu recommend:
```
~/qemu-raspi3$ git submodule init
~/qemu-raspi3$ git submodule update --recursive
~/qemu-raspi3$ 
```
Interestingly, I can build the mainline qemu as of today just fine (on the same machine, with the same tools), and when I do that, git submodule update fetches a whole bunch of modules.

Do you happen to know why git submodule doesn't seem to work in your repo? I'm at 08c87cd7.

Thanks.

**Comment by bztsrc** [comment]
Hi godmar,

Unfortunately I do not use Ubuntu, so I can't answer your question, neither can I provide qemu support. This patch is provided as-is, without any warranty.

Although I have an idea, if you have a qemu source that you can build, then make a copy of that, and overwrite the modified files from my repository in it. They are limited to only a bunch of files:

- include/hw/arm: bcm2836.h, bcm2837.h, raspi_platform.h
- hw/arm: Makefile.objs, bcm283*.c, raspi.c

I haven't introduced any new dependency, all my modifications should compile. But please keep in mind I'm not saying this for sure, I'm just suggesting a workaround.

According to submodules, I dunno, should work. I've forked the mainline qemu repo and only changed the files listed above, that's all. I haven't modified anything git related.

Good luck,
bzt

**Comment by godmar** [comment]
Thanks.  Do you remember roughly where you've forked off the mainline?  I wasn't able to find the commit from which you started, otherwise I would have tried to apply your changes as a patch to it.
(It doesn't appear to be a qemu commit: c6b01659ca2b24b3fcb76d19b16413198a951a89 )

**Comment by bztsrc** [comment]
Well, github says roughly 3 months ago, and for me it appears on the commit's page, saying on Oct 10 last year.
But I'm thinking of deleting this repo and repeat the whole fork+patch+push triumvirate on the latest qemu source, that should fix the submodule issue too.

**Comment by godmar** [comment]
That would be great.

I would like to contribute support for GPIOs - maybe a server with a webpage that shows the current state of output pins and allows the user to toggle input pins.

Do you know if something like this already exists?

**Comment by bztsrc** [comment]
Hey, I've minimalized the patch to hw/arm/bcm2836.c and hw/arm/raspi.c. It works perfectly for me with this version.

There's a strange error though if I apply the same to the latest mainline version (you have to add mc->min_cpus and mc->default_cpus in raspi3_machine_init() too because the multicore code have changed). According to "-d int" output, it's throwing an undefined instruction exception after every single instruction (but keeps working, and the exception is NOT passed to the VM). I assume the qemu guys f*cked something up with the code since Oct 10. So for now, I won't upgrade my repo.

According to the GPIO webpage, yes, [there is](https://github.com/bztsrc/phppe3/blob/master/vendor/phppe/RPi/composer.json). If you want to implement it in bare metal, there's a long way to go. First you'll have to implement a full USB stack. Then you'll have to implement a network card driver over USB. You'd need a working tcp/ip stack (could be lwip) and a http server (not complicated really) with a small WebAPI (to query and toggle pins). Finally you'll have to write the webpage in html+js.

**Comment by godmar** [comment]
Thanks for the link to RPi. I think you may have misunderstood what I meant (or I don't know what I'm talking about).  What I would like to have is a web server built into Qemu to which a browser can connect. On the website the user sees it will show the state of the GPIO pins in the SoC Qemu is currently emulating.  This is not a bare metal implementation. It's mainly a bit of http server code to qemu, hooking it up to however Qemu emulates the GPIO pins, and some JavaScript coding.  Do you know if anyone has done that?

**Comment by godmar** [comment]
I had to do:
```
git submodule add git://git.qemu-project.org/dtc.git dtc
```
as described [here](https://stackoverflow.com/a/9049703) 

Now I was able to build your code, but none of the kernel images I have run.

I've tried an SD card image from an SD card that works on real hardware (it contains the files from [here](https://web.stanford.edu/class/cs140e/assignments/0-blinky/), i.e. bootcode.bin + config.txt + start.elf + kernel8.img (obtained from activity-led-blink.bin). This fails with:

```
$ /opt/scratch/rpi3/bin/qemu-system-aarch64 -m 1024 -M raspi3 -serial stdio -kernel workingonhardware.img
VNC server running on 127.0.0.1:5900

(process:5115): GLib-ERROR **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmem.c:130: failed to allocate 18446744073063628800 bytes
```
before it crashes.
If I provide the kernel8.img (the renamed file activity-led-blink.bin from above site), then I see:
```
$ /opt/scratch/rpi3/bin/qemu-system-aarch64 -m 1024 -M raspi3 -serial stdio -kernel /media/gback/3761-3961/kernel8.img 
VNC server running on 127.0.0.1:5900
```
which could work, except that this kernel outputs something to the UART which I would expect to show up on the terminal (I see it on real hardware).  Should the UART work?

BTW, is there an example kernel I could build and test on both real hardware + your qemu to verify that the UART works correctly?

**Comment by godmar** [comment]
I read up a bit more and learned that start.elf, bootcode.bin are proprietary pieces of firmware that bootstrap the RPi, so what I was trying to do there wouldn't work.  I assume that the kernel specified with the -kernel option is a kernel image that would be loaded by start.elf if copied onto an RPi. That's at least how I understand your posting [here](https://www.raspberrypi.org/forums/viewtopic.php?t=195565#p1223722).

If that's true, I would expect 'activity-led-blink.bin' still to print something to stdout if '-serial stdio' maps the device's UART to stdio (and if the emulated UART works like the real one)

**Comment by bztsrc** [comment]
Hi godmar,

About webpage: yep, that's what I was talking about. If you want to control the pins over a web interface, you'd need a program that can access MMIO (either directly or through some interface) and also answers to http requests (either directly or as a cgi). The link I've sent does exactly that, shows the GPIO header with the current state of pins on a webpage and when you click on one of them it uses an AJAX WebAPI call to toggle that pin (with linux+nginx+php on raspberry side and javascript on client side). I don't see much point in a webserver built into qemu as vm does not have a real GPIO header to connect devices or leds to.

I can't give you qemu support and I don't know that activity-led-blink page you mentioned, but I can tell you this: your qemu arguments are bad, you've messed up kernel image with disk image as you've already figured out. Take a look at my [tutorial page](https://github.com/bztsrc/raspi3-tutorial#emulation) on proper invocation. If you use "-kernel" option, qemu won't use start.elf at all, it will only emulate the ARM boot up sequence. If you provide a disk image (which does not start with a valid ARM bytecode) don't expect any UART output but an unhandled "unknown instruction" exception. Now if you provide a valid kernel, then UART **_0_** should work. Real hardware can use UART **_1_** as well (connected to the same GPIO pins, but not redirected by qemu). Tutorials prefer UART1 as it's simpler to use. I wrote examples for both, [take a look](https://github.com/bztsrc/raspi3-tutorial/tree/master/05_uart0).

Cheers,
bzt

**Comment by godmar** [comment]
Thanks. I haven't actually looked at the source code for the kernel I've been testing - it's possible that it's using UART1 instead of 0. Your [tutorial example for UART0](https://github.com/bztsrc/raspi3-tutorial/tree/master/05_uart0) does work with my qemu build.

Actually, I can see UART1 too if I redirect it to a net console like so:
```
$ /opt/scratch/rpi3/bin/qemu-system-aarch64 -m 1024 -M raspi3 -serial stdio -chardev socket,host=localhost,port=4555,id=devforuart1 -serial chardev:devforuart1 -kernel kernel8.img
```
where 'kernel8.img' is your [UART1](https://github.com/bztsrc/raspi3-tutorial/tree/master/03_uart1) example. Nice!

Unfortunately, my kernel that works on real hardware still doesn't work - but that's ok, I can work from there.

Regarding:
_I don't see much point in a webserver built into qemu as vm does not have a real GPIO header to connect devices or leds to._

Well, isn't the idea of a virtual machine to be able to test kernels without or before using the actual hardware?   For instance, to test a driver such as [this one](https://kerneltweaks.wordpress.com/2014/06/09/led-blinking-driver-for-raspberry-pi/) without using hardware you have to be able to visualize the state of the emulated GPIO pins in qemu. Or look at the many examples where people try to boot baremetal programs and communicate with the outside world through LEDs connected to the GPIO pin, e.g. [here](https://raspberrypi.stackexchange.com/questions/36878/how-to-start-core-1-2-3-in-raspberry-pi-2).  Having the ability to see the state of the GPIO pins when running in qemu would be tremendously useful IMO.  The "real GPIO header" would be virtual - in a web page.

BTW, I'm not asking for your work time, just pointers if you have them, i.e., to where in Qemu the backend handles memory-mapped I/O.

**Comment by bztsrc** [comment]
Hi godmar,

Congrats! Good to hear it works! About your kernel, a guess. As qemu does not emulate the System Timer, almost all examples (haribote, circle64, LdB's, dwelch67's) ended up in an endless loop in their wait_msec() function. That's the reason why I come up with an ARM register only solution.

Thanks for the UART1 redirection arguments, I've experimented with that, but frankly I gave up and implemented UART0 instead. :-D

> Well, isn't the idea of a virtual machine to be able to test kernels without or before using the actual hardware?

Yeah, that was my point exactly. If you implement the webserver in a qemu module, you can't take that to an actual hardware. I've implemented a webinterface on the Raspberry which can be opened as a "website" from your phone's or tablet's browser so that you can control the things connected to the gpio pins.

> Having the ability to see the state of the GPIO pins when running in qemu would be tremendously useful IMO.

But now I understand better what you want to achieve. In that case you should take a look at the [gpio structure](https://github.com/bztsrc/qemu-raspi3/blob/master/include/hw/gpio/bcm2835_gpio.h#L19) in the [BCM2835PeripheralState](https://github.com/bztsrc/qemu-raspi3/blob/master/include/hw/arm/bcm2835_peripherals.h#L32) object, which is initialized [here](https://github.com/bztsrc/qemu-raspi3/blob/master/hw/arm/bcm2835_peripherals.c#L111). 

Although I haven't used it, there's a json based [qapi](https://github.com/bztsrc/qemu-raspi3/blob/master/qga/qapi-schema.json) in qemu, which seems to be a good candidate for backing a webapi. I mean one could implement a very minimal [tcp server](http://www.binarytides.com/server-client-example-c-sockets-linux/) in qemu doing nothing more than proxying json strings in http queries to this qapi module and sending the result json back in a http response. Once it's done, you only have to add gpio status to the qapi, and there's your REST api. I wouldn't put an entire website in qemu, I think it is enough to serve json only (see the [status and toggle](https://github.com/bztsrc/phppe3/blob/master/vendor/phppe/RPi/ctrl/rpi.php#L12) controllers in my code. Although they output plain text, because I'm lazy, could have been a json formatted text as well).

Sounds like a plan :-)
bzt

**Comment by godmar** [comment]
> As qemu does not emulate the System Timer, almost all examples (haribote, circle64, LdB's, dwelch67's) ended up in an endless loop in their wait_msec() function.

I don't know if that's the reason. I assume System Timer refers to the ["System Timer"](https://web.stanford.edu/class/cs140e/docs/BCM2835-ARM-Peripherals.pdf) in Section 12 pg 172.
That's 4 32-bit and 1 64-bit free running counters along with a match target for each that triggers an interupt - it would have to be mapped to whatever timer facilities qemu already provides. You've probably looked at this already.  Do you think that the System Timer of the BCM2835 is similar to the "Global Timer" described in the [Cortex-A9 manual](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0407f/CIHGECHJ.html)?  If so, would this need to be implemented similar to [a9gtimer.h](https://github.com/bztsrc/qemu-raspi3/blob/master/include/hw/timer/a9gtimer.h)?

Ultimately, a working -M raspi3 mode needs to emulate the hardware well enough so actual kernels run that make use of essential devices.

**Comment by bztsrc** [comment]
> I don't know if that's the reason. I assume System Timer refers to the "System Timer" in Section 12 pg 172.

Yes.

> That's 4 32-bit and 1 64-bit free running counters

That's the problem. On qemu it is not a running counter, but always returns a constant 0. Therefore delay loops like [this](https://github.com/moizumi99/RPiHaribote/blob/master/haribote/mylib.c#L30) and [this](https://github.com/rsta2/circle64/blob/master/lib/timer.cpp#L396) and [this](https://github.com/dwelch67/raspberrypi/blob/master/blinker02/blinker02.c#L31) will run forever. I've put extra check in [my tutorial](https://github.com/bztsrc/raspi3-tutorial/blob/master/07_delays/delays.c#L75) and implemented a [different delay loop](https://github.com/bztsrc/raspi3-tutorial/blob/master/07_delays/delays.c#L42). If your kernel uses ST, it's very likely it's hang on qemu because of it.

> Do you think that the System Timer of the BCM2835 is similar to the "Global Timer" described in the Cortex-A9 manual?

Looks like. Yes, using a similar implementation for the ST would solve the issue. I was looking at the HRNG code, thinking about duplicate it and return the qemu system time instead of a random number (and not implement interrupts in the first iteration). But I'm not into that as the qemu guys haven't merged my rpi code yet, so there's no point in bombing them with further patches.

> Ultimately, a working -M raspi3 mode needs to emulate the hardware well enough so actual kernels run that make use of essential devices.

Yes, I agree. But until then it's better than nothing :-) I've decided to use workarounds that run on qemu and real hardwware as well, and only expand qemu where it is unavoidable. So far this works for me.

bzt
